### PR TITLE
JBIDE-12575 Check if project should be validated before running the a…

### PR DESCRIPTION
**Pull request by rawagner**
…ctual validation

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
Fixes the issue described in this comment https://issues.jboss.org/browse/JBIDE-12575?focusedCommentId=12736216&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12736216

**Comment by adietish** [comment]
@robstryker you're the maintainer of base, right?

**Comment by jeffmaury** [comment]
@adietish Yes I'm on it now

**Comment by adietish** [comment]
@jeffmaury ok great

**Comment by jeffmaury** [comment]
@rawagner I'm getting confused because it fixes the case you mentioned but not the original use case (when CDI is enabled)

**Comment by rawagner** [comment]
@jeffmaury fix for the CDI is here https://github.com/jbosstools/jbosstools-javaee/pull/444

**Pull request merged**
