### PR TITLE
[JBIDE-26719] update default.version to 4.13.0.AM1

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
requires more modifications, don't have time to handle them. Will let Jboss Tools team handle it

**Comment by adietish** [comment]
@apupier what are the other changes that you deemed necessary?

**Comment by apupier** [comment]
> @apupier what are the other changes that you deemed necessary?

I don't know, that's why I stopped.
The error of the [PR](https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_pull_requests/job/jbosstools-base-Pull-Request/272/console) is pointing to Manifest.MF and pom.xml version of the modified plugin to upgrade and after that when i tried locally, it pointed to the parent of it. I also had another error with the feature.

it is normla that it is asking to upgrade it, just it seemes like there was always another artefact to upgrade so stopped. And also I don't know if the upgrade from 1.5.3 should be 1.5.4 or 1.6.0 or something else to align with some other more general version in Jboss Tools

**Comment by apupier** [comment]
closing. Issue fixed with https://github.com/jbosstools/jbosstools-base/pull/648
thanks

**Pull request closed without merging**
