### PR TITLE
added parser support for EL 3.0:  +=  ;  =  ->

### PR DESCRIPTION
**Pull request by thiesw**
- added unit tests
- improved output of parser unit test
- NOTE: no semantic and variable definition/resolving has been added
(yet)

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Please resubmit with the Sign-Off header for the PR to be accepted

**Comment by thiesw** [comment]
Is the sign-off in the last commit sufficient? Or what to do otherwise?

**Comment by jeffmaury** [comment]
> Is the sign-off in the last commit sufficient? Or what to do otherwise?

No Sign Off should be on every commit so you must rewrite history and force push then

**Comment by thiesw** [comment]
Build  has error "compare-version-with-baselines". That message is true but - in my opinion - changing plugin version is out of my scope for a (small) change. Maintainer of the plugin will do after incorporating all desired changes. Or am I wrong here?

**Comment by jeffmaury** [comment]
> Build has error "compare-version-with-baselines". That message is true but - in my opinion - changing plugin version is out of my scope for a (small) change. Maintainer of the plugin will do after incorporating all desired changes. Or am I wrong here?

Yes because we need the unit tests to run before accepting a PR. I will handle the version bump

**Comment by thiesw** [comment]
Did you perform the version bump manually in all the files (maybe search&replace) or is there a "bump version" command inside maven-pom?
Other question: When trying to build locally (`maven package` inside directory \jbosstools-base\common\plugins\org.jboss.tools.common.el.core\) I get the error
_Missing requirement: org.jboss.tools.common.el.core 3.17.200.qualifier requires 'osgi.bundle; org.jboss.tools.common.resref.core 0.0.0' but it could not be found_
Do I have to globally add another maven repository?

**Comment by jeffmaury** [comment]
> Did you perform the version bump manually in all the files (maybe search&replace) or is there a "bump version" command inside maven-pom? Other question: When trying to build locally (`maven package` inside directory \jbosstools-base\common\plugins\org.jboss.tools.common.el.core) I get the error _Missing requirement: org.jboss.tools.common.el.core 3.17.200.qualifier requires 'osgi.bundle; org.jboss.tools.common.resref.core 0.0.0' but it could not be found_ Do I have to globally add another maven repository?

No I run a tycho command from the common sub folder.
The error is normal as base is to be build from the root or you need to run `mvn install` if you want to run on a single plugin

**Comment by thiesw** [comment]
Ok. `maven verify` inside \jbosstools-base works. But I get the same compare-version-with-baselines error (as expected).
How can I change the version number myself to get a successful build? Maybe there is already a documentation for this?
Shall I include all the version bumped pom.xml in my pull request - would be required for the automated build to succeed. But this is in my opinion a bit large for a change inside a sub-sub-project. Or is it possible to skip just this compare-version-with-baselines for a local build? And what to include in the pull request then (because best would be to have a successful build for a submitted PR) ?
Maybe this info can/should be included in the README.md?

**Comment by jeffmaury** [comment]
> Ok. `maven verify` inside \jbosstools-base works. But I get the same compare-version-with-baselines error (as expected). How can I change the version number myself to get a successful build? Maybe there is already a documentation for this? Shall I include all the version bumped pom.xml in my pull request - would be required for the automated build to succeed. But this is in my opinion a bit large for a change inside a sub-sub-project. Or is it possible to skip just this compare-version-with-baselines for a local build? And what to include in the pull request then (because best would be to have a successful build for a submitted PR) ? Maybe this info can/should be included in the README.md?

See https://github.com/jbosstools/jbosstools-devdoc/blob/main/source/build_checks.adoc#compare-version-with-baselines

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
