### PR TITLE
JBIDE-25968 - if file.renameTo fails, try to copy it

### PR DESCRIPTION
**Pull request by robstryker**
Signed-off-by: Rob Stryker <rob@oxbeef.net>

### CODE REVIEW

**Comment by odockal** [comment]
@robstryker Looks good. Will try some more stuff as I am just writing itests for this wizard.

**Comment by odockal** [comment]
@robstryker The issue seems to be gone, it passes through my local itests for download runtime, once the pr-build is green, I am ok with merging, unless anyone objects anything...

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by jeffmaury** [comment]
@robstryker can you rebase it against master cause build fails because of Photon stuff

**Comment by odockal** [comment]
testPR

**Comment by robstryker** [comment]
Rebased

**Comment by odockal** [comment]
@jeffmaury @robstryker  I am giving +1 on this...

**Pull request merged**
