### PR TITLE
JBIDE-26655 Update sonar settings, removal of .settings folder from

### PR DESCRIPTION
**Pull request by jkopriva**
projects

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
Should be merged after: jbosstools/jbosstools-build#289

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
@jkopriva : failing with some versions check errors : 
[ERROR] Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.4.0:compare-version-with-baselines (default) on project org.jboss.tools.foundation.core: Version have moved backwards for (org.jboss.tools.foundation.core/1.5.4.AM1-v20191202-0852). Baseline has 1.5.4.Final-v20190930-1526-B3806) with delta: 0.0.0 -> [Help 1]

**Comment by sbouchet** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
@sbouchet Thank you!

**Pull request merged**
