### PR TITLE
JBIDE-19266 Batch validation problems QuickFixes

### PR DESCRIPTION
**Pull request by dazarov**
Code which detects the test environment moved from JVMProblemDetector to TestEnvironmentDetector

### CODE REVIEW

**Comment by alexeykazakov** [comment]
How is this related to Batch QuickFixes?

**Comment by dazarov** [comment]
Batch QuickFixes Tests - the first tests which use this new approach to detect test environment

**Comment by maxandersen** [comment]
eh...where do we have code that would want to have this kind of test ? 

that seems to be quite a codesmell ?

**Comment by maxandersen** [comment]
i.e. before this patch the code was private and unused (i.e. dead code)
so i'm curious to know why we ever would want code that behaves differently based on what test runner it is in - that would be IMO.

**Comment by dazarov** [comment]
We have tests for dialogs, which test how dialogs behave by default. So in tests dialog shoud not wait till user press buttons and finish button shoudl be presses automatically.
It's a matter of approach.
1. Have public method in dialogs which triggers test behaviour.
2. Have system property test sets it and dialog checks it.
3. Have general methos which detects that code was launchen in test environment...

#3 initially was made to test JVMProblemDetector, because #1 and #2 doesn't work where code is launched as early startup.

Now the main idea of using #3 is to have things done with less code and have universal method which can be used in different tests.
You don't need special test methods and you don't need to set system properties.

**Comment by dazarov** [comment]
this PR depends on https://github.com/jbosstools/jbosstools-base/pull/425

**Comment by alexeykazakov** [comment]
Rebased and pushed to master

**Pull request closed without merging**
