### PR TITLE
Added null reference check for JBossToolsUsageActivator.branding field.

### PR DESCRIPTION
**Pull request by whitingjr**
This PR is to resolve the issue reported at [JBDS-4788](https://issues.redhat.com/browse/JBDS-4788).
 The change adds a null reference condition.

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@whitingjr We need to pass DCO chcek, can you signoff your commit please?

**Comment by whitingjr** [comment]
@odockal done

**Comment by whitingjr** [comment]
@jeffmaury hope I got that correct. Is that what you intended ?

**Comment by jeffmaury** [comment]
@whitingjr this is not enough you need to update MANIFEST.MF and feature.xml as well

**Comment by odockal** [comment]
@whitingjr thanks, I suggest to upversion using maven:
`mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=2.2.300.qualifier`

**Comment by whitingjr** [comment]
@jeffmaury @odockal you guys are best placed to get this right. The build isn't working for me due to missing snapshot dependencies being available. That means I can't check if the MANIFEST is correct.

**Comment by whitingjr** [comment]
bah, I should have read the build instructions first.

**Comment by whitingjr** [comment]
@jeffmaury I did as you suggested. However after that I'm seeing this Maven [error](https://gist.github.com/whitingjr/11dcd09cf246a22bd93e6c14fd80e0b2).

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Pull request merged**
