### PR TITLE
prepare 4.19.1.AM1

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

### CODE REVIEW

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
build breaks because baseline check is removing the source feature that is needed by the site plugin...

**Comment by sbouchet** [comment]
builds needs to be run with -DbaselineCompareReplace=common to success ( not possible in this current PR ) 
@jeffmaury can you check/validate and then I'll make it possible in the master build.

**Comment by jeffmaury** [comment]
> 
> 
> builds needs to be run with -DbaselineCompareReplace=common to success ( not possible in this current PR )
> @jeffmaury can you check/validate and then I'll make it possible in the master build.

I don't understand why this is required ? Does the Jenkins PR check got this option as well ?

**Comment by sbouchet** [comment]
@jeffmaury i've updated the PR Check GitHub Action. i'll make another PR for master job CI.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
