### PR TITLE
JBIDE-27788: dont NPE if there's no current display/shell

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Tested on Windows. Worked for me. But seems common needs to be upversioned

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Version bump is invalid:
- only parent version seems updated
- several sub components have been changed (runtime, usage)
- version bump should be by micro 100 increment
- need proper common version bump

**Review by jeffmaury — CHANGES_REQUESTED** [review]
You doing it wrong. You bump base and not base.common.
So here is the trick:
- go to common sub folder
- mvn org.eclipse.tycho:tycho-versions-plugin:set-version -DnewVersion=3.16.100-SNAPSHOT -Dtycho.mode=maven
- update common version if jacoco/pom.xml

**Comment by adietish** [comment]
@sbouchet can't build the current version in master (not my PR). It keeps failing while having `jbosstools-target-plarforms`, `jbosstools-build` up-to-date and then doing `mvn clean install -DskipTests=true -DskipBaselineComparison=true`:

```
[DEBUG] Configuring mojo 'org.eclipse.tycho:tycho-p2-repository-plugin:2.2.0:assemble-repository' with basic configurator -->
[DEBUG]   (f) compress = true
[DEBUG]   (f) createArtifactRepository = true
[DEBUG]   (f) includeAllDependencies = false
[DEBUG]   (f) keepNonXzIndexFiles = true
[DEBUG]   (f) project = MavenProject: org.jboss.tools.base:base.site:4.5.0-SNAPSHOT @ /Users/andredietisheim/Documents/jboss-workspaces/jbosstools-github/jbosstools-base/site/pom.xml
[DEBUG]   (f) qualifier = v20210621-1021
[DEBUG]   (f) repositoryName = base.site
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@25dda53c
[DEBUG]   (f) xzCompress = true
[DEBUG] -- end configuration --
[DEBUG] No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from base.site raw:4.5.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.5.0-SNAPSHOT to org.eclipse.equinox.p2.iu; org.jboss.tools.common.oauth.feature.source.feature.group 0.0.0.; No solution found because the problem is unsatisfiable.]
[INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: base.site raw:4.5.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.5.0-SNAPSHOT
[ERROR]   Missing requirement: base.site raw:4.5.0.'SNAPSHOT'/format(n[.n=0;[.n=0;[-S]]]):4.5.0-SNAPSHOT requires 'org.eclipse.equinox.p2.iu; org.jboss.tools.common.oauth.feature.source.feature.group 0.0.0' but it could not be found
```
Any idea what I am missing?

**Comment by adietish** [comment]
@jeffmaury, @sbouchet: merging is blocked bcs of security/snik failure. Any insight what this is all about (clicking on Details won't help for me, I have no access and thus no insights)?

**Comment by jeffmaury** [comment]
> 
> 
> @jeffmaury, @sbouchet: merging is blocked bcs of security/snik failure. Any insight what this is all about (clicking on Details won't help for me, I have no access and thus no insights)?

False negative, please ignore

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
