### PR TITLE
jbide-22994: remove old Help->Report Problem dialog, replaced by AERI

### PR DESCRIPTION
**Pull request by bdshadow**

### CODE REVIEW

**Comment by nickboldt** [comment]
testPR

**Comment by nickboldt** [comment]
retest this please

**Comment by nickboldt** [comment]
retest this please

**Comment by alexeykazakov** [comment]
testPR

**Comment by bdshadow** [comment]
testPR

**Comment by bdshadow** [comment]
+ @robstryker, strangely, but local build is ok

**Comment by alexeykazakov** [comment]
testPR

**Comment by alexeykazakov** [comment]
All tests are finally passed. Merging.

**Pull request merged**
