### PR TITLE
Add maven nature to foundation.ui

### PR DESCRIPTION
**Pull request by dgolovin**
Fix adds maven nature to fondation.ui bundle to fix compilation
errors after importing bundle in eclipse workspace. Without
maven feature bundle have to be built by maven first to download
maven dependencies.

### CODE REVIEW

**Comment by alexeykazakov** [comment]
@robstryker @mmalina I don't think it's related but please take a look at the integration test failure:
`org.jboss.reddeer.core.exception.CoreLayerException: Item WildFly 9.0.1 Final does not exist in table
	at org.jboss.reddeer.core.handler.TableHandler.indexOf(TableHandler.java:151)
	at org.jboss.reddeer.swt.impl.table.AbstractTable.select(AbstractTable.java:173)
	at org.jboss.tools.runtime.reddeer.wizard.TaskWizardFirstPage.selectRuntime(TaskWizardFirstPage.java:22)
	at org.jboss.tools.runtime.as.ui.bot.test.download.RuntimeDownloadTestBase.processSelectingRuntime(RuntimeDownloadTestBase.java:71)
	at org.jboss.tools.runtime.as.ui.bot.test.download.ProjectRuntimeDownloadTestBase.downloadRuntime(ProjectRuntimeDownloadTestBase.java:16)
	at org.jboss.tools.runtime.as.ui.bot.test.download.ProjectRuntimeDownloadTestBase.downloadAndCheckRuntime(ProjectRuntimeDownloadTestBase.java:22)
	at org.jboss.tools.runtime.as.ui.bot.test.download.ProjectRuntimeDownloadTestBase.downloadAndCheckServer(ProjectRuntimeDownloadTestBase.java:32)
	at org.jboss.tools.runtime.as.ui.bot.test.download.SmokeRuntimeDownload.downloadWildfly90Final(SmokeRuntimeDownload.java:9)`

**Comment by mmalina** [comment]
@rhopp can you take a look at the test failure please?

**Comment by rhopp** [comment]
testPR

**Comment by mmalina** [comment]
@rhopp , any luck debugging why the test fails even though it looks fine from the screenshot?

**Comment by rhopp** [comment]
Not yet. Locally it runs fine. I was able to reproduce this error on that machine. Will need to investigate further.

**Comment by robstryker** [comment]
testPR

**Comment by robstryker** [comment]
* dd125ad12 - (HEAD -> main, origin/main) cherry-pick of PR 534 - Add maven nature to foundation.ui (25 seconds ago) <Rob Stryker>

**Pull request closed without merging**
