### PR TITLE
Primitives should not be boxed just for "String" conversion

### PR DESCRIPTION
**Pull request by apupier**
it has performance impact. Integer.toString, Character.toSring and so on
should be used.

Signed-off-by: Aurelien Pupier <apupier@redhat.com>

see https://sonarcloud.io/project/issues?id=org.jboss.tools%3Abase&open=AVpcTdT7GqtTGnUlDxWG&resolved=false&rules=squid%3AS2131&tags=performance&types=BUG

### CODE REVIEW

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
@apupier can you update because it does not compile (missing 1.8 level)

**Comment by jeffmaury** [comment]
testPR

**Comment by apupier** [comment]
testPR

**Comment by robstryker** [comment]
pushed to master after rebase etc

* 42d7bd9 - (fixPerformanceIssueReportedBySonar-primitivesShouldNotBeBoxedForString) Primitives should not be boxed just for "String" conversion (68 minutes ago) <Aurelien Pupier>

**Pull request closed without merging**
