### PR TITLE
JBIDE-25694 Add missing functionality to RedDeer plugin

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
@nickboldt can you please review and merge?

**Comment by nickboldt** [comment]
Reviewed and merged. @jkopriva should you have push rights to jbosstools-base? If so I can give you permission.

**Pull request merged**
