### PR TITLE
JBIDE-26938 - Fix the jbosstools-base blocker - the repo cannot be built after last commit

### PR DESCRIPTION
**Pull request by zcervink**
**JBIDE-26938 - Fix the following error:**
   [ERROR] Invalid value of default.version = 4.13.0.Final for parent = 4.14.0.AM1-SNAPSHOT !
   Must set default.version = 4.14.0.Final (or = 4.14.0.AM1) in this file:
   /Users/zcervink/git/jbosstools-base/foundation/plugins/org.jboss.tools.foundation.core/src/org/jboss/tools/foundation/core/properties/internal/currentversion.properties

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

**Jira:** https://issues.jboss.org/browse/JBIDE-26938
Please review @sbouchet @jeffmaury

### CODE REVIEW

**Comment by zcervink** [comment]
**Maven build is successfull after this fix:**

[INFO] Reactor Summary:
[INFO] 
[INFO] jbosstools-base 4.5.0-SNAPSHOT ..................... SUCCESS [  0.559 s]
[INFO] tests.all 3.7.103-SNAPSHOT ......................... SUCCESS [  0.020 s]
[INFO] tests.plugins 3.7.103-SNAPSHOT ..................... SUCCESS [  0.023 s]
[INFO] org.jboss.tools.tests 3.7.103-SNAPSHOT ............. SUCCESS [ 14.268 s]
[INFO] tests.tests 3.7.103-SNAPSHOT ....................... SUCCESS [  0.013 s]
[INFO] org.jboss.tools.tests.test 3.7.103-SNAPSHOT ........ SUCCESS [  0.239 s]
[INFO] tests.features 3.7.103-SNAPSHOT .................... SUCCESS [  0.017 s]
[INFO] foundation.all 1.5.4-SNAPSHOT ...................... SUCCESS [  0.013 s]
[INFO] foundation.features 1.5.4-SNAPSHOT ................. SUCCESS [  0.013 s]
[INFO] org.jboss.tools.foundation.license.feature 1.5.4-SNAPSHOT SUCCESS [  0.828 s]
[INFO] org.jboss.tools.test.feature 3.7.103-SNAPSHOT ...... SUCCESS [  0.219 s]
[INFO] foundation.plugins 1.5.4-SNAPSHOT .................. SUCCESS [  0.015 s]
[INFO] org.jboss.tools.foundation.core 1.5.4-SNAPSHOT ..... SUCCESS [  1.834 s]
[INFO] org.jboss.tools.foundation.checkup 1.5.4-SNAPSHOT .. SUCCESS [  1.681 s]
[INFO] org.jboss.tools.foundation.ui 1.5.4-SNAPSHOT ....... SUCCESS [  2.575 s]
[INFO] org.jboss.tools.foundation.security.linux 1.5.4-SNAPSHOT SUCCESS [  1.496 s]
[INFO] org.jboss.tools.foundation.help.ui 1.5.4-SNAPSHOT .. SUCCESS [  1.617 s]
[INFO] org.jboss.tools.foundation.feature 1.5.4-SNAPSHOT .. SUCCESS [  0.168 s]
[INFO] org.jboss.tools.foundation.security.linux.feature 1.5.4-SNAPSHOT SUCCESS [  1.195 s]
[INFO] foundation.tests 1.5.4-SNAPSHOT .................... SUCCESS [  0.022 s]
[INFO] org.jboss.tools.foundation.checkup.test 1.5.4-SNAPSHOT SUCCESS [  0.257 s]
[INFO] org.jboss.tools.foundation.core.test 1.5.4-SNAPSHOT  SUCCESS [  0.290 s]
[INFO] org.jboss.tools.foundation.help.test 1.5.4-SNAPSHOT  SUCCESS [  0.288 s]
[INFO] org.jboss.tools.foundation.ui.test 1.5.4-SNAPSHOT .. SUCCESS [  0.275 s]
[INFO] org.jboss.tools.foundation.test.feature 1.5.4-SNAPSHOT SUCCESS [  0.202 s]
[INFO] common.all 3.11.0-SNAPSHOT ......................... SUCCESS [  0.013 s]
[INFO] common.plugins 3.11.0-SNAPSHOT ..................... SUCCESS [  0.011 s]
[INFO] org.jboss.tools.common.core 3.11.0-SNAPSHOT ........ SUCCESS [  2.150 s]
[INFO] org.jboss.tools.common 3.11.0-SNAPSHOT ............. SUCCESS [  1.886 s]
[INFO] org.jboss.tools.common.resref.core 3.11.0-SNAPSHOT . SUCCESS [  1.626 s]
[INFO] org.jboss.tools.common.el.core 3.11.0-SNAPSHOT ..... SUCCESS [  2.198 s]
[INFO] org.jboss.tools.common.model.ui.capabilities 3.11.0-SNAPSHOT SUCCESS [  1.481 s]
[INFO] org.jboss.tools.common.model 3.11.0-SNAPSHOT ....... SUCCESS [  6.666 s]
[INFO] org.jboss.tools.common.text.xml 3.11.0-SNAPSHOT .... SUCCESS [  1.952 s]
[INFO] org.jboss.tools.common.validation 3.11.0-SNAPSHOT .. SUCCESS [  1.763 s]
[INFO] org.jboss.tools.common.ui 3.11.0-SNAPSHOT .......... SUCCESS [  2.242 s]
[INFO] org.jboss.tools.common.text.ext 3.11.0-SNAPSHOT .... SUCCESS [  2.516 s]
[INFO] org.jboss.tools.common.model.ui 3.11.0-SNAPSHOT .... SUCCESS [  5.034 s]
[INFO] org.jboss.tools.common.el.ui 3.11.0-SNAPSHOT ....... SUCCESS [  1.834 s]
[INFO] org.jboss.tools.common.gef 3.11.0-SNAPSHOT ......... SUCCESS [  1.889 s]
[INFO] org.jboss.tools.common.meta.ui 3.11.0-SNAPSHOT ..... SUCCESS [  0.569 s]
[INFO] org.jboss.tools.common.projecttemplates 3.11.0-SNAPSHOT SUCCESS [ 11.908 s]
[INFO] org.jboss.tools.common.resref.ui 3.11.0-SNAPSHOT ... SUCCESS [  1.795 s]
[INFO] org.jboss.tools.common.verification 3.11.0-SNAPSHOT  SUCCESS [  1.788 s]
[INFO] org.jboss.tools.common.verification.ui 3.11.0-SNAPSHOT SUCCESS [  1.805 s]
[INFO] org.jboss.tools.common.jdt.debug 3.11.0-SNAPSHOT ... SUCCESS [  1.532 s]
[INFO] org.jboss.tools.common.jdt.debug.ui 3.11.0-SNAPSHOT  SUCCESS [  1.686 s]
[INFO] org.jboss.tools.common.jdt 3.11.0-SNAPSHOT ......... SUCCESS [  1.616 s]
[INFO] org.jboss.tools.common.jdt.ui 3.11.0-SNAPSHOT ...... SUCCESS [  1.680 s]
[INFO] org.jboss.tools.common.mylyn 3.11.0-SNAPSHOT ....... SUCCESS [  1.413 s]
[INFO] org.jboss.tools.common.jaxb 3.11.0-SNAPSHOT ........ SUCCESS [  3.014 s]
[INFO] common.features 3.11.0-SNAPSHOT .................... SUCCESS [  0.011 s]
[INFO] org.jboss.tools.common.core.feature 3.11.0-SNAPSHOT  SUCCESS [  1.188 s]
[INFO] org.jboss.tools.common.feature 3.11.0-SNAPSHOT ..... SUCCESS [  1.189 s]
[INFO] org.jboss.tools.common.text.ext.feature 3.11.0-SNAPSHOT SUCCESS [  1.131 s]
[INFO] org.jboss.tools.common.ui.feature 3.11.0-SNAPSHOT .. SUCCESS [  1.208 s]
[INFO] org.jboss.tools.common.verification.feature 3.11.0-SNAPSHOT SUCCESS [  1.180 s]
[INFO] org.jboss.tools.common.all.feature 3.11.0-SNAPSHOT . SUCCESS [  0.301 s]
[INFO] common.test-framework 3.11.0-SNAPSHOT .............. SUCCESS [  0.010 s]
[INFO] org.jboss.tools.common.reddeer 3.11.0-SNAPSHOT ..... SUCCESS [  0.499 s]
[INFO] common.tests 3.11.0-SNAPSHOT ....................... SUCCESS [  0.016 s]
[INFO] org.jboss.tools.common.core.test 3.11.0-SNAPSHOT ... SUCCESS [  0.549 s]
[INFO] org.jboss.tools.common.test 3.11.0-SNAPSHOT ........ SUCCESS [  0.399 s]
[INFO] org.jboss.tools.common.el.core.test 3.11.0-SNAPSHOT  SUCCESS [  0.574 s]
[INFO] org.jboss.tools.common.model.test 3.11.0-SNAPSHOT .. SUCCESS [  0.467 s]
[INFO] org.jboss.tools.common.model.ui.test 3.11.0-SNAPSHOT SUCCESS [  0.385 s]
[INFO] org.jboss.tools.common.base.test 3.11.0-SNAPSHOT ... SUCCESS [  0.487 s]
[INFO] org.jboss.tools.common.validation.test 3.11.0-SNAPSHOT SUCCESS [  0.396 s]
[INFO] org.jboss.tools.common.verification.test 3.11.0-SNAPSHOT SUCCESS [  0.305 s]
[INFO] org.jboss.tools.common.verification.ui.test 3.11.0-SNAPSHOT SUCCESS [  0.405 s]
[INFO] org.jboss.tools.common.ui.test 3.11.0-SNAPSHOT ..... SUCCESS [  0.426 s]
[INFO] org.jboss.tools.common.text.ext.test 3.11.0-SNAPSHOT SUCCESS [  0.405 s]
[INFO] org.jboss.tools.common.mylyn.test 3.8.100-SNAPSHOT . SUCCESS [  0.225 s]
[INFO] org.jboss.tools.common.all.test.feature 3.8.200-SNAPSHOT SUCCESS [  0.441 s]
[INFO] org.jboss.tools.common.jdt.feature 3.11.0-SNAPSHOT . SUCCESS [  1.277 s]
[INFO] org.jboss.tools.common.mylyn.feature 3.11.0-SNAPSHOT SUCCESS [  1.167 s]
[INFO] stacks.all 1.4.102-SNAPSHOT ........................ SUCCESS [  0.011 s]
[INFO] stacks.plugins 1.4.102-SNAPSHOT .................... SUCCESS [  0.010 s]
[INFO] org.jboss.tools.stacks.core 1.4.102-SNAPSHOT ....... SUCCESS [  2.168 s]
[INFO] stacks.tests 1.4.102-SNAPSHOT ...................... SUCCESS [  0.013 s]
[INFO] org.jboss.tools.stacks.core.test 1.4.102-SNAPSHOT .. SUCCESS [  0.294 s]
[INFO] stacks.features 1.4.102-SNAPSHOT ................... SUCCESS [  0.011 s]
[INFO] org.jboss.tools.stacks.core.feature 1.4.102-SNAPSHOT SUCCESS [  1.091 s]
[INFO] org.jboss.tools.stacks.core.test.feature 1.4.102-SNAPSHOT SUCCESS [  0.122 s]
[INFO] runtime.all 3.5.0-SNAPSHOT ......................... SUCCESS [  0.011 s]
[INFO] runtime.plugins 3.5.0-SNAPSHOT ..................... SUCCESS [  0.011 s]
[INFO] org.jboss.tools.runtime.core 3.5.0-SNAPSHOT ........ SUCCESS [  1.761 s]
[INFO] org.jboss.tools.runtime.ui 3.5.0-SNAPSHOT .......... SUCCESS [  2.148 s]
[INFO] runtime.test-framework 3.5.0-SNAPSHOT .............. SUCCESS [  0.010 s]
[INFO] org.jboss.tools.runtime.reddeer 3.5.0-SNAPSHOT ..... SUCCESS [  0.210 s]
[INFO] runtime.tests 3.5.0-SNAPSHOT ....................... SUCCESS [  0.015 s]
[INFO] org.jboss.tools.runtime.test 3.5.0-SNAPSHOT ........ SUCCESS [  0.337 s]
[INFO] runtime.features 3.5.0-SNAPSHOT .................... SUCCESS [  0.012 s]
[INFO] org.jboss.tools.runtime.core.feature 3.5.0-SNAPSHOT  SUCCESS [  1.140 s]
[INFO] org.jboss.tools.runtime.test.feature 3.5.0-SNAPSHOT  SUCCESS [  0.136 s]
[INFO] usage.all 2.2.202-SNAPSHOT ......................... SUCCESS [  0.010 s]
[INFO] usage.plugins 2.2.202-SNAPSHOT ..................... SUCCESS [  0.009 s]
[INFO] org.jboss.tools.usage 2.2.202-SNAPSHOT ............. SUCCESS [  1.651 s]
[INFO] usage.tests 2.2.202-SNAPSHOT ....................... SUCCESS [  0.010 s]
[INFO] org.jboss.tools.usage.test 2.2.202-SNAPSHOT ........ SUCCESS [  0.251 s]
[INFO] usage.features 2.2.202-SNAPSHOT .................... SUCCESS [  0.012 s]
[INFO] org.jboss.tools.usage.feature 2.2.202-SNAPSHOT ..... SUCCESS [  1.104 s]
[INFO] org.jboss.tools.usage.test.feature 2.2.202-SNAPSHOT  SUCCESS [  0.104 s]
[INFO] base.site 4.5.0-SNAPSHOT ........................... SUCCESS [  8.327 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:45 min
[INFO] Finished at: 2019-11-05T13:12:11+01:00
[INFO] ------------------------------------------------------------------------

**Comment by sbouchet** [comment]
@zcervink : be aware that the PR build was unsuccessfull because of a baseline check :
Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:1.4.0:compare-version-with-baselines (default) on project org.jboss.tools.foundation.core: Version have moved backwards for (org.jboss.tools.foundation.core/1.5.4.AM1-v20191105-1213). Baseline has 1.5.4.Final-v20190930-1526-B3806)

did you enabled it on your local build ?

**Comment by jeffmaury** [comment]
Because foundation has changed, you need to bump it.

**Comment by zcervink** [comment]
@sbouchet On local build the **mvn clean install -DskipTests=true** results in the same fail, but the **mvn clean install -DskipTests=true -DskipBaselineComparison=true** finishes with ALL GREEN SUCCESSES. I have experienced this "Baseline" error several times in the past, I was told by @jkopriva only to add the **-DskipBaselineComparison=true** parameter to my mvn command on my localhost to compile successfully and after some time the issue has disappeared.

**Comment by sbouchet** [comment]
I agree with @jeffmaury, this error must be fixed by bumping the version. we don't allow to disable it on master builds.

**Comment by zcervink** [comment]
@sbouchet @jeffmaury I have discussed this 'bumping' issue with @odockal (I have not done it before). Now I know how to do it and I have completed the bumping in the foundation. Build on localhost is now GREEN, we wait until the Jenkins finishes.

**Comment by zcervink** [comment]
@sbouchet @jeffmaury Build is now successful, foundation has been bumped, nothing else needs to be bumped.

**Comment by zcervink** [comment]
@jeffmaury I have bumped the smallest number in the version, how more micro it should be? See my changes:
1.5.**4**-SNAPSHOT   ---->   1.5.**5**-SNAPSHOT


And I am little bit confused, you wrote, that you prefer micro bump and then you approved this PR. Should I edit this PR and bump ip to 1.5.**401**-SNAPSHOT (according to @odockal it is almost the same as bum it to 1.5.**5**-SNAPSHOT), or are we gonna merge for this time?

**Comment by jeffmaury** [comment]
Sorry I was wrong I want minor to be increased so should be 1.6.0-SNAPSHOT

**Comment by zcervink** [comment]
@jeffmaury Thank you for you information, I have bumped the version to 1.6.0-SNAPSHOT. Build on localhost and Jenkins are now green.

**Pull request merged**
